name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    #   - name: SCP build folder
    #     run: |
    #       scp -P ${{ secrets.SERVER_PORT }} -r ./dist/* \
    #       ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/family.regmi.de
      - name: Deploy via rsync
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.SERVER_PORT }}" \
          ./dist/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/family.regmi.de